[WIP] Courses News (#169)
fit-ctu-discord/honza-botner pull request #176
Opened 2021-09-23 21:06 UTC by ostorc

Solves #169

2021-09-26 19:01 UTC, tenhobi reviewed
Seems cool.

2021-09-26 19:01 UTC, tenhobi commented on src/HonzaBotner.Discord.Services/Jobs/NewsJobProvider.cs
> +        public const string Key = "reminders-trigger";
Change the key.

2021-09-26 19:01 UTC, tenhobi commented on src/HonzaBotner.Discord.Services/Jobs/NewsJobProvider.cs
> +        public static string CronExpression => Cron.Hourly();
Can we make like 10 minutes lookup?

2021-09-26 19:01 UTC, tenhobi commented on src/HonzaBotner.Services.Contract/Dto/NewsConfigDto.cs
> +    }
```suggestion
    public record NewsConfigDto(int Id, string Name, string Source, DateTime LastFetched, string NewsProviderType, string PublisherType, params ulong[] Channels);
```

2021-09-26 19:01 UTC, tenhobi commented on src/HonzaBotner.Services.Contract/Dto/NewsConfigDto.cs
> +    }
Also, why add "Dto" to the name? Other records don't have it.

2021-09-26 19:01 UTC, tenhobi commented on src/HonzaBotner.Services.Contract/Dto/NewsDto.cs
> +    public record NewsDto(string Link, string Author, string Title, string Content, DateTime CreatedAt);
Same, why include "Dto" in the name?

2021-09-26 19:10 UTC, ostorc commented on src/HonzaBotner.Services.Contract/Dto/NewsConfigDto.cs
> +    }
Hmm, I think we can change it, since it is already in namespace *.Dto.

2021-09-27 16:54 UTC, ostorc commented on src/HonzaBotner.Discord.Services/Jobs/NewsJobProvider.cs
> +        public static string CronExpression => Cron.Hourly();
Changed

2021-09-27 17:18 UTC, ostorc commented
TODO: 
- [ ] Store somehow last loaded news from Courses (for each source!)
- [ ] Modify `since` parameter in Courses provider to load -1 day since last load time, it has to be like that due to implementation of Courses API 
- [ ] Show only new post according to lastly displayed news

2021-09-27 20:57 UTC, ostorc commented
Still missing registering to the cron and running it inside it. But that is only about one line, for now you can run with commands `::news`

2021-11-24 22:03 UTC, tenhobi requested changes

2021-11-24 22:03 UTC, tenhobi commented on Packages.props
> +	<PackageReference Update="Html2Markdown" Version="4.0.0.427" />
```suggestion
        <PackageReference Update="Shouldly" Version="4.0.3" />
	      <PackageReference Update="Html2Markdown" Version="4.0.0.427" />
```

2021-11-24 22:03 UTC, tenhobi commented on src/HonzaBotner.Services/CvutAuthorizationService.cs
> +            UriBuilder uriBuilder = new(tokenUri);
TODO

2022-09-17 15:06 UTC, closed without merging