Add mute/unmute
fit-ctu-discord/honza-botner pull request #57
Opened 2020-10-30 13:28 UTC by albru123

Adds basic mute/unmute commands that assign mute role to specified user.

This partially implements #35 except for the muted user listing (as I don't know what formatting should be used).

2020-10-30 17:00 UTC, tenhobi requested changes

2020-10-30 21:49 UTC, albru123 commented on src/HonzaBotner.Discord.Services/ServiceCollectionExtensions.cs
> +            serviceCollection.AddSingleton<MuteRoleHelper>();
This way the MuteRoleHelper can fetch the MuteRole ID directly. I felt like this solution was better, but let me know what you think. I could also hide it behind an interface, but I don't think it's really necessary (thoughts @tenhobi?)

2021-02-12 20:36 UTC, ostorc commented
@albru123 Can you look at this again and bring it up to date?

2021-02-22 09:20 UTC, tenhobi commented
Merging requirements with #31.

2021-02-22 09:20 UTC, closed without merging